### ISSUE TITLE
mesos.o.b.e nginx proxies only read DNS at startup, eventually proxy to wrong mesos master

### ISSUE THREAD

**Issue by chriskuehl** [ocf/puppet#104]
When a leader election occurs, the DNS name `leader.mesos` changes. But unfortunately, nginx only resolves the name once, at startup, and so it continues to proxy to a master which is no longer leading (which then issues a redirect to the new leader, but with the internal (non-proxied) hostname and port, and everything just doesn't work).

Seems like the commercial version of nginx supports re-resolving (boo), but there are some tricks online to get the open-source version to re-resolve, too.

**Comment by jvperrin** [comment]
https://tenzer.dk/nginx-with-dynamic-upstreams/ seems relevant, all that we'd need to do from the looks of things is do something like this (if possible using the puppet nginx module of course):

    resolver ns.ocf.berkeley.edu;
    set $upstream_endpoint http://leader.mesos:5050;
    location / {
        proxy_pass $upstream_endpoint;
    }

Also not sure using `resolver` is entirely necessary, I'm guessing it's not since all the servers are set up to use it as their resolver anyway.

**Comment by chriskuehl** [comment]
yup that worked perfectly
