### ISSUE TITLE
Replace Apache with Nginx for mirrors

### ISSUE THREAD

**Issue by ethanhs** [ocf/puppet#1133]
Our mirrors server [currently uses Apache for serving our mirrors content](https://github.com/ocf/puppet/blob/master/modules/ocf_mirrors/manifests/init.pp#L64). Apache is rather inefficient at serving static content compared to Nginx, and caching in Apache is apparently not great either.

We should replace Apache with Nginx, which should cache things better (less disk I/O) and generally be better at using resources on fallingrocks.

**Comment by dkess** [comment]
We originally used Apache because being an Apache mirror had specific requirements that could only be fulfilled by using Apache httpd:

https://github.com/ocf/puppet/blob/a7f00b6ef4d067d57b977f1f54d520e6abe52a6e/modules/ocf_mirrors/manifests/init.pp#L87-L88

Though the link is broken now, so maybe this isn't true anymore.

As long as we're still complying with each project's requirements, this is probably fine to do (if the Apache restriction is the /only/ blocker, we could drop them from our archive), though I'd be surprised if it had a meaningful effect on our disk IO.
